# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "golang_docker")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "71c6cdbcecbda8bfc099b07e0952d40a98bfdb2ac6d547bfe518bc33a00f3c74",
    strip_prefix = "rules_docker-e8780651b14abb8806029992247af328ac70d638",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/e8780651b14abb8806029992247af328ac70d638.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

# For dockerfile_image rule tests
load("@io_bazel_rules_docker//contrib:dockerfile_build.bzl", "dockerfile_image")

load("//:revisions.bzl", "BASE", "DISTROLESS_BASE", "GO_INSTALLER")

dockerfile_image(
    name = "image",
    dockerfile = "//:Dockerfile",
    build_args = {
        "base_digest": BASE.sha256,
        "distroless_digest": DISTROLESS_BASE.sha256,
        "go_version": GO_INSTALLER.revision,
        "go_sha256": GO_INSTALLER.sha256,
        "build_tag": "xingao-test",
    }
)

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_load",
)

container_load(
    name = "loaded_image",
    file = "@image//image:dockerfile_image.tar",
)